language: julia
julia:
  - 1.0
  - 1.1
  - nightly
  
notifications:
  email: false
  
addons:
  apt:
    packages:
      - libcfitsio3
      - gfortran
      - mpich
      - libmpich-dev
      - curl

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
