language: julia
julia:
  - 0.6
notifications:
  email: false
addons:
  apt:
    packages:
      - libcfitsio3
before_script:
  - julia -e 'Pkg.clone("https://github.com/ziotom78/Healpix.jl")'
after_success:
  - julia -e 'cd(Pkg.dir("Stripeline")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Stripeline")); include(joinpath("docs", "make.jl"))'
